
import { Meal, DietaryType, BookingService, Language, Story } from './types';

// Exchange rate: 1 USD = 15 GHS
export const EXCHANGE_RATE = 15;

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    menu: "Meal Plans",
    consultations: "Consultations",
    stories: "Success Stories",
    signIn: "Sign In",
    profile: "Profile",
    signOut: "Sign Out",
    addToOrder: "Add to Order",
    customizeAdd: "Customize & Add",
    viewPlan: "View Plan Details",
    bookSession: "Book a Session",
    yourOrder: "Your Order",
    checkout: "Checkout",
    subtotal: "Subtotal",
    total: "Total",
    heroTitle: "Fuel Your Body, Heal Your Life",
    heroSubtitle: "Personalized Ghanaian-fusion meal plans and expert dietitian consultations.",
    viewMenu: "View Menu",
    bookConsultation: "Book Consultation",
    expertGuidance: "Expert Guidance",
    tailoredMacros: "Tailored Macros",
    chefPrepared: "Chef Prepared",
    successStories: "Success Stories & Reviews",
    contact: "Contact",
    quickLinks: "Quick Links",
    all: "All Items",
    regular: "Single Meals",
    bronze: "Bronze (3-Day)",
    premium: "Premium (7-Day)",
    singleMeal: "Single Meal",
    ingredients: "Ingredients",
    portionSize: "Portion Size",
    standard: "Standard",
    large: "Large",
    specialInstructions: "Special Instructions",
    shippingDetails: "Shipping Details",
    securePayment: "Secure Payment",
    payOrder: "Pay & Order",
    orderConfirmed: "Order Confirmed!",
    returnHome: "Return Home",
    addOns: "Add-ons",
    submitStory: "Share Your Story",
    pendingApproval: "Pending Approval",
    dashboard: "Admin Dashboard",
    price: "Price"
  },
  tw: { // Twi (Akan)
    home: "Fie",
    menu: "Aduane",
    consultations: "Afotu",
    stories: "Adanseɛ",
    signIn: "Kɔ Mu",
    profile: "Wo Ho Sɛm",
    signOut: "Pue",
    addToOrder: "Fa Ka Ho",
    customizeAdd: "Yɛ No Sɛnea Wopɛ",
    viewPlan: "Hwɛ Plan No",
    bookSession: "Pɛ Bere",
    yourOrder: "W'ade Tɔ",
    checkout: "Tua Ka",
    subtotal: "Ne Nyinaa",
    total: "Ka",
    heroTitle: "Ma Wo Honam Ahoɔden",
    heroSubtitle: "Aduane a ɛyɛ ma wo apɔwmuden fi Ghana abenfoɔ hɔ.",
    viewMenu: "Hwɛ Aduane",
    bookConsultation: "Hu Ɔbenfoɔ",
    expertGuidance: "Afotu",
    tailoredMacros: "Sɛnea Wopɛ",
    chefPrepared: "Abenfoɔ Na Ɛnoae",
    successStories: "Adanseɛ",
    contact: "Nkitahodie",
    quickLinks: "Link",
    all: "Ne Nyinaa",
    regular: "Aduane Baako",
    bronze: "Bronze (Nna 3)",
    premium: "Premium (Nna 7)",
    singleMeal: "Aduane",
    ingredients: "Nnoɔma",
    portionSize: "Kɛseyɛ",
    standard: "Ketewa",
    large: "Kɛseɛ",
    specialInstructions: "Ahyɛdeɛ",
    shippingDetails: "Faako a yɛmfa mmrɛ wo",
    securePayment: "Tua Sika",
    payOrder: "Tua na Tɔ",
    orderConfirmed: "W'atɔ Wie!",
    returnHome: "Kɔ Fie",
    addOns: "Nnoɔma a Wopɛ",
    submitStory: "Ka Wo Sɛm",
    pendingApproval: "Yɛretwɛn",
    dashboard: "Admin Dashboard",
    price: "Ne Boɔ"
  },
  fr: {
    home: "Accueil",
    menu: "Repas",
    consultations: "Consultations",
    stories: "Témoignages",
    signIn: "Se Connecter",
    profile: "Profil",
    signOut: "Déconnexion",
    addToOrder: "Ajouter",
    customizeAdd: "Personnaliser",
    viewPlan: "Voir le Plan",
    bookSession: "Réserver",
    yourOrder: "Votre Commande",
    checkout: "Payer",
    subtotal: "Sous-total",
    total: "Total",
    heroTitle: "Nourrissez Votre Corps",
    heroSubtitle: "Plans de repas personnalisés ghanéens et consultations d'experts.",
    viewMenu: "Voir Menu",
    bookConsultation: "Réserver",
    expertGuidance: "Conseils d'Experts",
    tailoredMacros: "Macros Adaptées",
    chefPrepared: "Préparé par Chef",
    successStories: "Témoignages",
    contact: "Contact",
    quickLinks: "Liens Rapides",
    all: "Tout",
    regular: "Repas Uniques",
    bronze: "Bronze (3 Jours)",
    premium: "Premium (7 Jours)",
    singleMeal: "Repas Unique",
    ingredients: "Ingrédients",
    portionSize: "Portion",
    standard: "Standard",
    large: "Grand",
    specialInstructions: "Instructions",
    shippingDetails: "Livraison",
    securePayment: "Paiement Sécurisé",
    payOrder: "Payer et Commander",
    orderConfirmed: "Commande Confirmée!",
    returnHome: "Retour",
    addOns: "Suppléments",
    submitStory: "Partagez Votre Histoire",
    pendingApproval: "En Attente",
    dashboard: "Tableau de Bord",
    price: "Prix"
  },
  es: {
    home: "Inicio",
    menu: "Menú",
    consultations: "Consultas",
    stories: "Historias",
    signIn: "Iniciar Sesión",
    profile: "Perfil",
    signOut: "Cerrar Sesión",
    addToOrder: "Añadir",
    customizeAdd: "Personalizar",
    viewPlan: "Ver Plan",
    bookSession: "Reservar",
    yourOrder: "Tu Pedido",
    checkout: "Pagar",
    subtotal: "Subtotal",
    total: "Total",
    heroTitle: "Alimenta Tu Cuerpo",
    heroSubtitle: "Planes de comida personalizados de Ghana y consultas de expertos.",
    viewMenu: "Ver Menú",
    bookConsultation: "Reservar Cita",
    expertGuidance: "Guía Experta",
    tailoredMacros: "Macros a Medida",
    chefPrepared: "Preparado por Chef",
    successStories: "Historias de Éxito",
    contact: "Contacto",
    quickLinks: "Enlaces Rápidos",
    all: "Todos",
    regular: "Comidas",
    bronze: "Bronce (3 Días)",
    premium: "Premium (7 Días)",
    singleMeal: "Comida Individual",
    ingredients: "Ingredientes",
    portionSize: "Porción",
    standard: "Estándar",
    large: "Grande",
    specialInstructions: "Instrucciones",
    shippingDetails: "Envío",
    securePayment: "Pago Seguro",
    payOrder: "Pagar y Pedir",
    orderConfirmed: "¡Pedido Confirmado!",
    returnHome: "Volver",
    addOns: "Adicionales",
    submitStory: "Comparte tu Historia",
    pendingApproval: "Pendiente",
    dashboard: "Panel de Admin",
    price: "Precio"
  },
  zh: {
    home: "首页",
    menu: "菜单",
    consultations: "咨询",
    stories: "成功案例",
    signIn: "登录",
    profile: "个人资料",
    signOut: "登出",
    addToOrder: "加入订单",
    customizeAdd: "定制并添加",
    viewPlan: "查看计划",
    bookSession: "预约",
    yourOrder: "您的订单",
    checkout: "结账",
    subtotal: "小计",
    total: "总计",
    heroTitle: "滋养您的身体",
    heroSubtitle: "个性化的加纳风味膳食计划和专家营养师咨询。",
    viewMenu: "查看菜单",
    bookConsultation: "预约咨询",
    expertGuidance: "专家指导",
    tailoredMacros: "定制宏量营养",
    chefPrepared: "主厨烹制",
    successStories: "成功案例",
    contact: "联系我们",
    quickLinks: "快速链接",
    all: "全部",
    regular: "单餐",
    bronze: "铜牌 (3天)",
    premium: "高级 (7天)",
    singleMeal: "单餐",
    ingredients: "配料",
    portionSize: "份量",
    standard: "标准",
    large: "大份",
    specialInstructions: "特别说明",
    shippingDetails: "配送详情",
    securePayment: "安全支付",
    payOrder: "支付并下单",
    orderConfirmed: "订单已确认！",
    returnHome: "返回首页",
    addOns: "附加项",
    submitStory: "分享您的故事",
    pendingApproval: "待批准",
    dashboard: "管理仪表板",
    price: "价格"
  }
};

const commonAddOns = [
  { name: 'Avocado', price: 1.5 },
  { name: 'Boiled Egg', price: 0.5 },
  { name: 'Grilled Chicken', price: 3.0 },
  { name: 'Fried Plantain', price: 1.0 }
];

export const MEALS: Meal[] = [
  // --- Regular Meals (Ghanaian/Fusion) ---
  {
    id: 'm1',
    name: 'Jollof Quinoa Power Bowl',
    description: 'A healthy twist on the classic Ghanaian Jollof using organic quinoa, served with grilled chicken breast and coleslaw.',
    price: 12.00,
    calories: 450,
    protein: 25,
    carbs: 55,
    fats: 12,
    image: 'https://images.unsplash.com/photo-1623341214823-6bb306a470cd?auto=format&fit=crop&q=80&w=800',
    tags: [DietaryType.GLUTEN_FREE, DietaryType.BALANCED],
    ingredients: ['Quinoa', 'Tomato Stew', 'Grilled Chicken', 'Cabbage', 'Carrots', 'Ginger', 'Garlic', 'Habenero'],
    category: 'Regular',
    inStock: true,
    availableAddOns: commonAddOns
  },
  {
    id: 'm2',
    name: 'Grilled Tilapia & Garden Veggies',
    description: 'Fresh Volta tilapia grilled with local spices, served with steamed broccoli, carrots, and a side of roasted sweet potato.',
    price: 15.50,
    calories: 420,
    protein: 45,
    carbs: 20,
    fats: 18,
    image: 'https://images.unsplash.com/photo-1544025162-d76690b67f61?auto=format&fit=crop&q=80&w=800', // Grilled Fish
    tags: [DietaryType.PESCATARIAN, DietaryType.GLUTEN_FREE, DietaryType.PALEO],
    ingredients: ['Tilapia', 'Ginger', 'Kpakpo Shito', 'Sweet Potato', 'Broccoli', 'Carrots', 'Onion'],
    category: 'Regular',
    inStock: true,
    availableAddOns: [{ name: 'Extra Tilapia', price: 6.0 }, ...commonAddOns]
  },
  {
    id: 'm3',
    name: 'Waakye Protein Salad',
    description: 'Deconstructed Waakye bowl with black-eyed peas, sorghum leaves rice, boiled egg, avocado, and shito-spiced dressing.',
    price: 10.00,
    calories: 550,
    protein: 22,
    carbs: 60,
    fats: 20,
    image: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&q=80&w=800',
    tags: [DietaryType.GLUTEN_FREE, DietaryType.BALANCED],
    ingredients: ['Rice', 'Millet Stalks', 'Black-eyed Peas', 'Avocado', 'Egg', 'Tomato', 'Spicy Pepper Sauce'],
    category: 'Regular',
    inStock: true,
    availableAddOns: [{ name: 'Wele (Cow Skin)', price: 1.0 }, ...commonAddOns]
  },
  {
    id: 'm4',
    name: 'Spicy Chicken Suya Skewers',
    description: 'Lean chicken breast coated in nutty suya spice blend, grilled to perfection with onions and bell peppers.',
    price: 11.50,
    calories: 320,
    protein: 38,
    carbs: 8,
    fats: 15,
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&q=80&w=800',
    tags: [DietaryType.KETO, DietaryType.GLUTEN_FREE, DietaryType.PALEO],
    ingredients: ['Chicken Breast', 'Peanut Powder', 'Cayenne', 'Ginger', 'Onion', 'Bell Peppers'],
    category: 'Regular',
    inStock: true,
    availableAddOns: commonAddOns
  },
  {
    id: 'm5',
    name: 'Garden Egg Stew & Boiled Yam',
    description: 'Traditional savory stew made with garden eggs (African eggplant) and fish flakes, served with slice of yam.',
    price: 9.00,
    calories: 380,
    protein: 15,
    carbs: 65,
    fats: 10,
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&q=80&w=800', // Pizza removed, using generic healthy stew placeholder if specific not found, but trying yam/stew look
    tags: [DietaryType.BALANCED, DietaryType.PESCATARIAN],
    ingredients: ['Garden Eggs', 'Yam', 'Palm Oil (Minimal)', 'Onions', 'Koobi (Salted Fish)', 'Tomatoes'],
    category: 'Regular',
    inStock: true,
    availableAddOns: [{ name: 'Extra Yam', price: 1.0 }, ...commonAddOns]
  },
  {
    id: 'm6',
    name: 'Tropical Coconut & Mango Parfait',
    description: 'Fresh coconut cream layered with diced mangoes, papaya, and a dusting of toasted cashew nuts.',
    price: 6.50,
    calories: 250,
    protein: 5,
    carbs: 25,
    fats: 16,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a029177b?auto=format&fit=crop&q=80&w=800',
    tags: [DietaryType.VEGAN, DietaryType.PALEO, DietaryType.GLUTEN_FREE],
    ingredients: ['Coconut Cream', 'Mango', 'Papaya', 'Cashew Nuts', 'Lime Zest', 'Honey'],
    category: 'Regular',
    inStock: true
  },

  // --- Bronze Plans (3 Days) ---
  {
    id: 'b1',
    name: '3-Day Ashanti Detox',
    description: 'Light soups and grilled proteins inspired by Ashanti cuisine to cleanse and reset.',
    price: 85.00,
    calories: 1400,
    protein: 90,
    carbs: 40,
    fats: 80,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=80&w=800',
    tags: [DietaryType.KETO, DietaryType.GLUTEN_FREE],
    ingredients: ['Light Soup', 'Grilled Chicken', 'Garden Eggs', 'Pepper Soup', 'Avocado Salad'],
    category: 'Bronze',
    inStock: true
  },
  {
    id: 'b2',
    name: '3-Day Accra Cleanse',
    description: 'Plant-based vibrant meals featuring beans, plantains, and fresh tropical salads.',
    price: 75.00,
    calories: 1350,
    protein: 50,
    carbs: 160,
    fats: 45,
    image: 'https://images.unsplash.com/photo-1511690656952-34342d5c2899?auto=format&fit=crop&q=80&w=800',
    tags: [DietaryType.VEGAN, DietaryType.GLUTEN_FREE],
    ingredients: ['Black-eyed Peas', 'Plantain', 'Millet Porridge', 'Fruit Salad', 'Green Leafy Stews'],
    category: 'Bronze',
    inStock: true
  },

  // --- Premium Plans (7 Days) ---
  {
    id: 'p1',
    name: '7-Day Gold Coast Wellness',
    description: 'The ultimate Ghanaian healthy experience. 14 meals mixing traditional flavors with modern nutrition.',
    price: 195.00,
    calories: 1650,
    protein: 115,
    carbs: 145,
    fats: 70,
    image: 'https://images.unsplash.com/photo-1543362906-ac1b96633e38?auto=format&fit=crop&q=80&w=800',
    tags: [DietaryType.BALANCED],
    ingredients: ['Red Red', 'Grilled Snapper', 'Fonio', 'Kontomire Stew', 'Fresh Juice Blends'],
    category: 'Premium',
    inStock: true
  },
  {
    id: 'p2',
    name: '7-Day Volta Paleo',
    description: 'Grain-free, dairy-free plan focusing on fresh fish, lean meats, and root vegetables.',
    price: 220.00,
    calories: 1750,
    protein: 145,
    carbs: 85,
    fats: 95,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=800',
    tags: [DietaryType.PALEO, DietaryType.GLUTEN_FREE],
    ingredients: ['Tilapia', 'Yam', 'Cassava', 'Eggs', 'Coconut Oil', 'Nuts'],
    category: 'Premium',
    inStock: true
  }
];

export const STORIES: Story[] = [
  {
    id: 's1',
    userId: 'u1',
    authorName: 'Abena Koranteng',
    content: 'The 3-Day Ashanti Detox was exactly what I needed. I feel lighter and more energetic. The light soup was authentic yet healthy!',
    rating: 5,
    approved: true,
    date: '2023-10-15',
    role: 'user',
    image: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 's2',
    userId: 'u2',
    authorName: 'Kojo Asante',
    content: 'Finally, a meal prep service that understands Ghanaian seasoning. The Jollof Quinoa is a game changer.',
    rating: 5,
    approved: true,
    date: '2023-11-02',
    role: 'user',
    image: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 's3',
    userId: 'u3',
    authorName: 'Sarah Jenkins',
    content: 'As an expat in Accra, I struggled to find healthy local options. The Dietitian bridged that gap perfectly.',
    rating: 4,
    approved: true,
    date: '2023-09-20',
    role: 'user',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 's4',
    userId: 'u4',
    authorName: 'Kwame Mensah',
    content: 'Pending review content...',
    rating: 4,
    approved: false,
    date: '2023-12-01',
    role: 'user'
  }
];

export const SERVICES: BookingService[] = [
  {
    id: 's1',
    name: 'Initial Consultation',
    durationMin: 60,
    price: 80,
    description: 'A comprehensive review of your health history, dietary habits, and goals.'
  },
  {
    id: 's2',
    name: 'Follow-up Session',
    durationMin: 30,
    price: 45,
    description: 'Review progress, adjust meal plans, and address new challenges.'
  },
  {
    id: 's3',
    name: 'Meal Planning Workshop',
    durationMin: 45,
    price: 60,
    description: 'Learn how to prep meals effectively for your specific dietary needs.'
  }
];

export const SYSTEM_INSTRUCTION = `You are NutriAI, a friendly and knowledgeable virtual assistant for The Dietitian, a dietitian and meal delivery service based in Ghana. 
Your goal is to help users find meals from our menu that fit their goals and answer basic nutrition questions. 
We serve Ghanaian dishes with a healthy twist (Jollof, Waakye, Red Red).
The menu items are: ${MEALS.map(m => `${m.name} (${m.tags.join(', ')} - $${m.price})`).join('; ')}. 
Be concise, encouraging, and helpful. If a user asks about booking, guide them to the booking page. 
Do not provide medical advice.`;
